apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::484110161423:user/aarete-iam-user
      username: aarete-iam-user
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::484110161423:role/aarete-test-iam-LimitedAccessRoleForRmlApplication-LBNV3M931NLT
      groups:
        - system:masters
    - rolearn: arn:aws:iam::484110161423:role/Aarete-EKS-Test-NodeInstanceRole-1AQQ1KZRVWF9G
      groups:
        - system:masters
