apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: value1
      username: value2
      groups:
        - system:masters
  mapRoles: |
    - rolearn: value3
      groups:
        - system:masters
    - rolearn: value4
      groups:
        - system:masters
